dev_m_study_task_manage_list:
    pattern: /index
    defaults: { _controller: DevMStudyTaskManageBundle:TaskManage:list }

dev_m_study_task_manage_create:
    pattern: /create
    defaults: { _controller: DevMStudyTaskManageBundle:TaskManage:create }

dev_m_study_task_manage_update:
    pattern: /update/{id}
    defaults: { _controller: DevMStudyTaskManageBundle:TaskManage:update }
    requirements:
        page:  \d+

dev_m_study_task_manage_delete:
    pattern: /delete/{id}
    defaults: { _controller: DevMStudyTaskManageBundle:TaskManage:delete }
    requirements:
        page:  \d+
