parameters:
#    dev_m_study_task_manage.example.class: DevMStudy\TaskManageBundle\Example

services:
#    dev_m_study_task_manage.example:
#        class: %dev_m_study_task_manage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
